name: test_cat_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  freezed_annotation: ^0.11.0+1
  flutter_bloc: ^6.0.1
  get_it: ^4.0.4
  injectable: ^1.0.4
  dartz: ^0.9.1
  auto_route: ^0.6.7
  google_sign_in: ^4.5.4
  cached_network_image: ^2.3.2+1
  network_to_file_image: ^2.3.5
  extended_image: ^1.1.2
  flutter_svg: ^0.18.1
  shared_preferences: ^0.5.12
  flutter_facebook_login: ^3.0.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  lint: ^1.2.0
  freezed: ^0.11.5
  auto_route_generator: ^0.6.8
  injectable_generator: ^1.0.4
  built_value_generator: ^7.1.0
  chopper_generator: ^3.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/